### ISSUE TITLE
fails to run as cron command

### ISSUE THREAD

**Issue by frozonfreak** [backup-manager/laravel-4#55]
I have the below command set up for backing up

`db:backup --database=mysql --destination=s3 --destinationPath=`date +\test/%Y%m%d%H%M%S.sql`--compression=gzip`

Code works fine as command

Fails with local.ERROR: exception 'BackupManager\ShellProcessing\ShellProcessFailed' with message 'sh: mysqldump: command not found when the same is run from scheduler. 

Any suggestions.

**Comment by ShawnMcCool** [comment]
I'm guessing that the PATH variable isn't set because it's probably not being loaded. Put the PHP command into a bash script called `backup.sh` (with full path to artisan file) then in the crontab reference something like:

`0 2 * * * bash /whatever/backup.sh`

See if that works. By calling bash you're loading up your environment which includes your PATH variable which tells it where to find binaries.

**Comment by frozonfreak** [comment]
Yep my scheduler works fine. 
I have other mailing scheduler commands which works fine. 

Its just this backup command that fails.

**Comment by ShawnMcCool** [comment]
Either mysqldump doesn't exist. Which it does, because you can run the command manually. 

Or, it's not in path during the cron's run. The instructions above should resolve that.

**Comment by frozonfreak** [comment]
Hi @ShawnMcCool ,  Thanks for the solution, 
You solution dint work, adding bash profile to backup.sh did work

**Comment by davidnathanael** [comment]
@frozonfreak i have the same issue, what do you mean by "adding bash profile to backup.sh did work"

can you share a code snippet pls, thanks

**Comment by ShawnMcCool** [comment]
Here's an example of a cron job that I use

0 2 * * * /bin/bash /home/forge/eventsourcery.com/backup.sh 

and the bash script

```
#!/bin/bash

cd /home/forge/eventsourcery.com
/usr/bin/php artisan db:backup --database=mysql --destination=s3 --destinationPath=eventsourcery-`date +%Y-%m-%d_%H-%M-%S` --compression=gzip
```
